#MusicItem {
    qproperty-textColor: rgba(127,127,127,100%);
    qproperty-titleColor: rgba(41,41,41,100%);
    qproperty-highlightText: white;
    qproperty-background: #fbfbfb;
    qproperty-alternateBackground: #ffffff;
    qproperty-highlightedBackground:  #2ca7f8;
    qproperty-animationPrefix: ":/common/animation/playing/black";
    qproperty-highlightAnimationPrefix: ":/common/animation/playing/white";
}
