.TH deepin\-music 1 "2021-03-03" "Deepin"

.SH NAME
deepin\-music \- Deepin music playing application

.SH SYNOPSIS
.B deepin\-music

.SH DESCRIPTION
.B Deepin Music
is an application developed by Deepin Technology Team which focused on local music playing. It brings all brand new UI design, extreme playing experience, and it has local music scanning and lyric sync functions, etc.

.SH OPTIONS
This program does not accept any command line options.

.SH SEE ALSO
https://www.deepin.org/en/original/deepin-music/

.SH AUTHOR
.B deepin\-music
is written by Deepin Technology Co., Ltd.

This manual page was written by
.MT zouya@uniontech.com
Yangfl
.ME
for the Debian Project (but may be used by others).
