#TitleLeft{
    border: 0px solid rgba(255,255,255,0.3);
}

#TitleRight{
    border: 2px solid rgba(255,0,255,0.3);
}

#TitleBack{
    border-image: url(:/image/back_normal.png);
}
#TitleBack:hover{
    border-image: url(:/image/back_hover.png);
}
#TitleBack:pressed{
    border-image: url(:/image/back_press.png);
}

#TitleIcon {
    image: url(:/common/image/deepin_music.svg)
}

#DEditInsideFrame {
    background: transparent;
}

