Dtk--Widget--DTitlebar {
  background: qlineargradient(x1: 1, y1: 0, x2: 1, y2: 1, stop: 0 rgba(255, 255, 255, 100%), stop: 1 rgba(248, 248, 248, 100%));
  border-bottom: 1px solid rgba(0, 0, 0, 10%);
}

Dtk--Widget--DTitlebar[viewname="lyric"] {
  background: qlineargradient(x1: 0 y1: 0, x2: 0 y2: 1, stop: 0 rgba(0, 0, 0, 20%), stop: 1 rgba(0, 0, 0, 20%));
  border-top: 1px solid rgba(255, 255, 255, 5%);
  border-bottom: 1px solid rgba(0, 0, 0, 10%);
}


/* ------ #DTitlebarDWindowOptionButton  ------ */

#DTitlebarDWindowOptionButton {
  qproperty-normalPic: url(:/images/light/images/window/menu_normal.svg);
  qproperty-hoverPic: url(:/images/light/images/window/menu_hover.svg);
  qproperty-pressPic: url(:/images/light/images/window/menu_press.svg);
}

#DTitlebarDWindowOptionButton[viewname="lyric"] {
  qproperty-normalPic: url(:/images/dark/images/window/menu_normal.svg);
  qproperty-hoverPic: url(:/images/dark/images/window/menu_hover.svg);
  qproperty-pressPic: url(:/images/dark/images/window/menu_press.svg);
}


/* ------ #DTitlebarDWindowMinButton ------ */

#DTitlebarDWindowMinButton {
  qproperty-normalPic: url(:/images/light/images/window/minimize_normal.svg);
  qproperty-hoverPic: url(:/images/light/images/window/minimize_hover.svg);
  qproperty-pressPic: url(:/images/light/images/window/minimize_press.svg);
}

#DTitlebarDWindowMinButton[viewname="lyric"] {
  qproperty-normalPic: url(:/images/dark/images/window/minimize_normal.svg);
  qproperty-hoverPic: url(:/images/dark/images/window/minimize_hover.svg);
  qproperty-pressPic: url(:/images/dark/images/window/minimize_press.svg);
}


/* ------ #DTitlebarDWindowMaxButton ------ */

#DTitlebarDWindowMaxButton[isMaximized=true] {
  qproperty-normalPic: url(:/images/light/images/window/unmaximize_normal.svg);
  qproperty-hoverPic: url(:/images/light/images/window/unmaximize_hover.svg);
  qproperty-pressPic: url(:/images/light/images/window/unmaximize_press.svg);
}

#DTitlebarDWindowMaxButton[isMaximized=false] {
  qproperty-normalPic: url(:/images/light/images/window/maximize_normal.svg);
  qproperty-hoverPic: url(:/images/light/images/window/maximize_hover.svg);
  qproperty-pressPic: url(:/images/light/images/window/maximize_press.svg);
}

#DTitlebarDWindowMaxButton[isMaximized=true][viewname="lyric"] {
  qproperty-normalPic: url(:/images/dark/images/window/unmaximize_normal.svg);
  qproperty-hoverPic: url(:/images/dark/images/window/unmaximize_hover.svg);
  qproperty-pressPic: url(:/images/dark/images/window/unmaximize_press.svg);
}

#DTitlebarDWindowMaxButton[isMaximized=false][viewname="lyric"] {
  qproperty-normalPic: url(:/images/dark/images/window/maximize_normal.svg);
  qproperty-hoverPic: url(:/images/dark/images/window/maximize_hover.svg);
  qproperty-pressPic: url(:/images/dark/images/window/maximize_press.svg);
}


/* ------ #DTitlebarDWindowCloseButton ------ */

#DTitlebarDWindowCloseButton {
  qproperty-normalPic: url(:/images/light/images/window/close_normal.svg);
  qproperty-hoverPic: url(:/images/light/images/window/close_hover.svg);
  qproperty-pressPic: url(:/images/light/images/window/close_press.svg);
}

#DTitlebarDWindowCloseButton[viewname="lyric"] {
  qproperty-normalPic: url(:/images/dark/images/window/close_normal.svg);
  qproperty-hoverPic: url(:/images/dark/images/window/close_hover.svg);
  qproperty-pressPic: url(:/images/dark/images/window/close_press.svg);
}
